name: CI

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        typo3: [ '^10.4' ]
        php: [ '7.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version ${{ matrix.php }}
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          php -v

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.php }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Run php linter
        run: composer ci:php:lint

      - name: Run php-cs-fixer
        run: composer ci:php:php-cs-fixer

      - name: Run phpstan
        run: composer ci:php:phpstan

  tag-valid:
    name: Check for a valid tag
    # Tests must be successful
    needs: tests
    # Run only, when there is a tag in the event
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    # Save status for use in other jobs
    outputs:
      status: ${{ steps.check-tag.outputs.match }}

    steps:
      # Check for a valid tag
      - name: Check if trigger is a valid tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=match::true
          fi

  ter-release:
    name: TYPO3 TER Release
    needs: tag-valid
    if: needs.tag-valid.outputs.status == 'true'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']

    env:
      TYPO3_EXTENSION_KEY: groupdelegation
      TYPO3_USER: ${{ secrets.TYPO3_USER }}
      TYPO3_PASSWORD: ${{ secrets.TYPO3_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.TYPO3_EXTENSION_KEY }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring, xml, soap, zip, curl

      - name: Install TYPO3 TER client
        run: composer global require helhum/ter-client --prefer-dist --no-progress

      - name: Remove .git folder
        run: |
          rm -rf ./$TYPO3_EXTENSION_KEY/.git

      - name: Upload EXT:${{ env.TYPO3_EXTENSION_KEY }} as ${{ github.event.ref }} to TER
        run: |
          php $HOME/.composer/vendor/bin/ter-client upload "$TYPO3_EXTENSION_KEY" ./$TYPO3_EXTENSION_KEY -u "$TYPO3_USER" -p "$TYPO3_PASSWORD" -m "${{ github.event.head_commit.message }}"



